spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/JProject
    username: sa
    password:
    driver-class-name: org.h2.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: mjuAppSW@gmail.com
    password: spzzwnqvufoeccnc
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
      logging.level:
        org.hibernate.SQL: debug
#        org.hibernate.type: trace
