spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/JProject
    username: sa
    password:
    driver-class-name: org.h2.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: mjuAppSW@gmail.com
    password: spzzwnqvufoeccnc
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
      logging.level:
        org.hibernate.SQL: debug
#        org.hibernate.type: trace

  data:
    redis:
      host: localhost #로컬
      port: 6379 #로컬

  cloud:
    aws:
      credentials:
        access-key: AKIA3PML3BK7VR3XIKIG #로컬 저장소용
        secret-key: fx+ieiYkajue+Ihasuw2wR6y2/xraY6OUna6/UPg #로컬 저장소용
      region:
        static: ap-northeast-2
        auto: false
      stack:
        auto: false
      s3:
        bucket: j-project-2023

  sql:
    init:
      mode: always



